version: '3'

services:
  db:
    container_name: rtws-postgres
    image: postgres:latest
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - db/.env.db
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/scripts/:/docker-entrypoint-initdb.d/

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: rtws-zookeeper
    ports:
      - "22181:2181"
    env_file:
      - .env.kafka
  mq:
    image: confluentinc/cp-kafka:latest
    container_name: rtws-mq
    depends_on:
      - zookeeper
    ports:
      - "29092:29092"
    env_file:
      - .env.kafka

  postgres-to-kafka:
    image: python:3-alpine
    container_name: rtws-postgres-to-kafka
    depends_on:
      - db
      - mq
#    restart: always
    build:
      context: ./service/postgres-to-kafka
      dockerfile: Dockerfile
#    volumes:
#      - ./service/postgres-to-kafka:/app
    env_file:
      - ./db/.env.db


  stripe-integration:
    container_name: rtws-stripe-integration
    build:
      context: .
      dockerfile: ./service/stripe-integration/Dockerfile
    restart: always
    depends_on:
      - db
      - mq
#    volumes:
#      - ./service/stripe-integration:/app
    env_file:
      - .env
      - ./service/stripe-integration/.env.stripe
      - ./db/.env.db

volumes:
  postgres_data:
  zookeeper_data:
  zookeeper_log:
